name: publish to npm

on:
  release:
    types:
      - prereleased

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, build, and test
        run: |
          npm config set //registry.npmjs.org/:_authToken="${NPM_TOKEN}"
          npm i -g npm
          npm install
          npm publish --tag beta
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
